version: '3.1'
services:
  order-service:
    image: okandilmit/order-service:latest
    container_name: order-service
    ports:
      - 8081:8081
    working_dir: /opt/app
    command: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/order-service.jar"]

