version: '3.1'
services:
  payment-service:
    image: okandilmit/payment-service:latest
    container_name: payment-service
    ports:
      - 8082:8082
    working_dir: /opt/app
    command: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/payment-service.jar"]

